AntmJS/antm

CHANGELOG.md
lerna.json
packages/babel-preset/package.json

chore(release): publish 0.2.0

---

CHANGELOG.md
lerna.json
packages/babel-preset/package.json
packages/eslint/package.json
packages/stylelint/package.json

chore(release): publish 0.3.0

---

lerna.json
packages/babel-preset/package.json
packages/eslint/package.json
packages/stylelint/package.json

chore(release): publish 0.3.1

---

lerna.json
packages/babel-preset/package.json
packages/eslint/package.json
packages/stylelint/package.json

* 删除无效包依赖 ([c4c6528](https://github.com/AntmJS/antm/commit/c4c6528cd07498829472e50a331f1118a8e948ec))
* 添加默认插件 ([978e7f5](https://github.com/AntmJS/antm/commit/978e7f5ca7bc152a85ca7173a6cb3107b3ffa0c4))

chore(release): publish 0.4.0

---

lerna.json
packages/babel-preset/package.json
packages/eslint/package.json
packages/stylelint/package.json

* 修复stylelint校验时报错 ([9d2aa84](https://github.com/AntmJS/antm/commit/9d2aa8422f6feeb7da2a4f631980e22461b83e54))
* 删除无效包依赖 ([c4c6528](https://github.com/AntmJS/antm/commit/c4c6528cd07498829472e50a331f1118a8e948ec))
* 添加默认插件 ([978e7f5](https://github.com/AntmJS/antm/commit/978e7f5ca7bc152a85ca7173a6cb3107b3ffa0c4))

chore(release): publish 0.4.1

---

lerna.json
packages/babel-preset/package.json
packages/eslint/package.json
packages/stylelint/package.json

* 移除相同组件 ([d0ef404](https://github.com/AntmJS/antm/commit/d0ef404754020d08032dea2525cdfafc5ce8d148))
* 修复stylelint校验时报错 ([9d2aa84](https://github.com/AntmJS/antm/commit/9d2aa8422f6feeb7da2a4f631980e22461b83e54))
* 删除无效包依赖 ([c4c6528](https://github.com/AntmJS/antm/commit/c4c6528cd07498829472e50a331f1118a8e948ec))
* 添加默认插件 ([978e7f5](https://github.com/AntmJS/antm/commit/978e7f5ca7bc152a85ca7173a6cb3107b3ffa0c4))

chore(release): publish 0.4.2

---

lerna.json
packages/babel-preset/package.json
packages/eslint/package.json
packages/iconfont/package.json
packages/stylelint/package.json

* 生成可以在Taro里面使用的Iconfont ([d6f65f7](https://github.com/AntmJS/antm/commit/d6f65f7a1b2f4a42079e7b5cc246d220cae65d2c))
* 移除相同组件 ([d0ef404](https://github.com/AntmJS/antm/commit/d0ef404754020d08032dea2525cdfafc5ce8d148))
* 修复stylelint校验时报错 ([9d2aa84](https://github.com/AntmJS/antm/commit/9d2aa8422f6feeb7da2a4f631980e22461b83e54))
* 删除无效包依赖 ([c4c6528](https://github.com/AntmJS/antm/commit/c4c6528cd07498829472e50a331f1118a8e948ec))
* 添加默认插件 ([978e7f5](https://github.com/AntmJS/antm/commit/978e7f5ca7bc152a85ca7173a6cb3107b3ffa0c4))

chore(release): publish 0.5.0

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/iconfont/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 禁止使用color-named ([b4bee69](https://github.com/AntmJS/antm/commit/b4bee690cb503a8d009f174319e5cc7284d885ba))
* 生成可以在Taro里面使用的Iconfont ([d6f65f7](https://github.com/AntmJS/antm/commit/d6f65f7a1b2f4a42079e7b5cc246d220cae65d2c))
* 移除相同组件 ([d0ef404](https://github.com/AntmJS/antm/commit/d0ef404754020d08032dea2525cdfafc5ce8d148))
* 修复stylelint校验时报错 …

chore(release): publish 0.6.0

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/iconfont/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 禁止使用color-named ([b4bee69](https://github.com/AntmJS/antm/commit/b4bee690cb503a8d009f174319e5cc7284d885ba))
* 生成可以在Taro里面使用的Iconfont ([d6f65f7](https://github.com/AntmJS/antm/commit/d6f65f7a1b2f4a42079e7b5cc246d220cae65d2c))
* 移除相同组件 …

chore(release): publish 0.6.1

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/iconfont/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 禁止使用color-named ([b4bee69](https://github.com/AntmJS/antm/commit/b4bee690cb503a8d009f174319e5cc7284d885ba))
* 生成可以在Taro里面使用的Iconfont …

chore(release): publish 0.7.0

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/iconfont/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 禁止使用color-named ([b4bee69](https://github.com/AntmJS/antm/commit/b4bee690cb503a8d0 …

chore(release): publish 0.8.0

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/iconfont/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 禁止使用color-named ([b4bee69](https://github.com/AntmJS/antm/commit/b4bee690cb503a8d0 …

chore(release): publish 0.8.1

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/iconfont/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 修复参数异常 ([7aa73e9](https://github.com/AntmJS/antm/commit/7aa73e9b039922e651a65142ea1cbc3ba30be45c))
* 添加缓存包 ([83c3868](https://github.com/AntmJS/antm/commit/83c3868abe08d7bb534e27cd91 …

chore(release): publish 0.8.2

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/global-state/package.json
packages/iconfont/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 初始化 ([4f271a1](https://github.com/AntmJS/antm/commit/4f271a19f33c18dd94c287462e9782c388e67d70))
* 添加global-state ([fe4d313](https://github.com/AntmJS/antm/commit/fe4d31390fb2c85ee09154087caf9b77cad06a8d))
* 修复参数异常 ([7aa73e9](https://github.com/AntmJS/antm/commit/7aa73e9b039922e651a65142ea1cbc3ba30be45c))
* 更新名称 ([f482c3c](https://github.com/AntmJS/antm/commit/f482c3ce2b734e715b6c8e …

chore(release): publish 0.9.0

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/global-state/package.json
packages/iconfont/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* provider未注册之前调用hooks做一个错误提示 ([7975b2b](https://github.com/AntmJS/antm/commit/7975b2b8120736d9106bbfd3eedc19caea9272d0))
* 初始化 ([4f271a1](https://github.com/AntmJS/antm/commit/4f271a19f33c18dd94c287462e9782c388e67d70))
* 添加global-state ([fe4d313](https://github.com/AntmJS/antm/commit/fe4d31390fb2c85ee09154087caf9b77cad06a8d))
* 修复参数异常 ([7aa73e9](https://github.com/AntmJS/antm/commit/7aa73e9b039922e651a65142ea1cbc3ba30be45c))
* 修复参数未定义异常 …

chore(release): publish 0.9.1

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/global-state/package.json
packages/iconfont/package.json
packages/plugin-icestark/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 添加Taro支持飞冰的微前端架构iceStark ([28c9822](https://github.com/AntmJS/antm/commit/28c98228da7d0c360bf4fb3fc3fcba286086060e))
* provider未注册之前调用hooks做一个错误提示 ([7975b2b](https://github.com/AntmJS/antm/commit/7975b2b8120736d9106bbfd3eedc19caea9272d0))
* 初始化 ([4f271a1](https://github.com/AntmJS/antm/commit/4f271a19f33c18dd94c287462e9782c388e67d70))
* 添加global-state ([fe4d313](https://github.com/AntmJS/antm/commit/fe4d31390fb2c85ee09154087caf9b77cad06a8d))
* 修复参数异常 ([7aa73e9](https://github.com/AntmJS/antm/commit/7aa73e9b039922e651a65142ea1cbc3ba30be45c))
* 添加百度和QQ小程序的支持 …

chore(release): publish 0.10.0

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/global-state/package.json
packages/iconfont/package.json
packages/mini-fix/package.json
packages/plugin-icestark/package.json
packages/plugin-mini-fix/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 添加插件解决各小程序端返回的query decode情况不一致的问题，trace包删除decode逻辑，统一由插件来处理 ([b115d58](https://github.com/AntmJS/antm/commit/b115d58a5f8a829e79c037e5ccd2da70dd749696))
* 添加Taro支持飞冰的微前端架构iceStark ([28c9822](https://github.com/AntmJS/antm/commit/28c98228da7d0c360bf4fb3fc3fcba286086060e))
* provider未注册之前调用hooks做一个错误提示 ([7975b2b](https://github.com/AntmJS/antm/commit/7975b2b8120736d9106bbfd3eedc19caea9272d0))
* 初始化 ([4f271a1](https://github.com/AntmJS/antm/commit/4f271a19f33c18dd94c287462e9782c388e67d70))
* 添加global-state ([fe4d313](https://github.com/AntmJS/antm/commit/fe4d31390fb2c85ee09154087caf9b77cad06a8d))
* 修复参数异常 ([7aa73e9](https://github.com/AntmJS/antm/commit/7aa73e9b039922e651a65142ea1cbc3ba30be4 …

chore(release): publish 1.0.0

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/global-state/package.json
packages/iconfont/package.json
packages/mini-fix/package.json
packages/plugin-icestark/package.json
packages/plugin-mini-fix/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/utils/package.json

* 修复H5获取路径多一个？ ([3b65ae3](https://github.com/AntmJS/antm/commit/3b65ae32742c45b5c81f808a67576a69335f793b))
* 更新插件严格匹配入口文件 ([5b6acbc](https://github.com/AntmJS/antm/commit/5b6acbc8064e01255310cfc39206ae012433883c))
* 添加插件解决各小程序端返回的query decode情况不一致的问题，trace包删除decode逻辑，统一由插件来处理 ([b115d58](https://github.com/AntmJS/antm/commit/b115d58a5f8a829e79c037e5ccd2da70dd749696))
* 添加Taro支持飞冰的微前端架构iceStark ([28c9822](https://github.com/AntmJS/antm/commit/28c98228da7d0c360bf4fb3fc3fcba286086060e))
* provider未注册之前调用hooks做一个错误提示 ([7975b2b](https://github.com/AntmJS/antm/commit/7975b2b8120736d9106bbfd3eedc19caea9272d0))
* 初始化 ([4f271a1](https://github.com/AntmJS/antm/commit/4f271a19f33c18dd94c287462e9782c388 …

chore(release): publish 1.0.1

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/global-state/package.json
packages/iconfont/package.json
packages/mini-fix/package.json
packages/plugin-icestark/package.json
packages/plugin-mini-fix/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/unite/package.json
packages/utils/package.json

* 更新import/order顺序 ([e0973a6](https://github.com/AntmJS/antm/commit/e0973a6d99b94e56591c7ad9238438b448901fc3))
* 错误被捕获的时候环境为development的状态下error出来 ([bcd47d2](https://github.com/AntmJS/antm/commit/bcd47d268a55a05d62bcd9026995761216b778d4))
* unite包添加错误收集及设置的方法 ([0f146f6](https://github.com/AntmJS/antm/commit/0f146f6d07a336941fe0d175b75ba585d10a0f0d))
* 优化主题变量 ([83be1bf](https://github.com/AntmJS/antm/commit/83be1bf9566f1ce6647a96071a49d97542e0da87))
* 优化图片选择器 ([d9dd104](https://github.com/AntmJS/antm/commit/d9dd10437447569a535cdebbd30903a43d5a24fa))
* 修复border设置过细在支付宝端不展示的问题 ([0d0a0dc](https://github.com/AntmJS/antm/commit/0d0a0dc152883eabb95ad940763a7c0e9e9f05ab))
* 增加组件 ([4a3a0fe](https://github.com/AntmJS/antm/commit/4a3a0fea4fe4c196f2d465bba60f4147168b1b59))
* 修复不可点击按钮的样式问题 …

chore(release): publish 1.9.4

---

lerna.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/global-state/package.json
packages/iconfont/package.json
packages/mini-fix/package.json
packages/plugin-icestark/package.json
packages/plugin-mini-fix/package.json
packages/rapper/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/unite/package.json
packages/utils/package.json
packages/warning/package.json

* 添加eslint支持graphql ([e9e4e8f](https://github.com/AntmJS/antm/commit/e9e4e8fd755b9b81a08afec2c9967877522d0c7a))
* eslint规则内的eslint-plugin-prettier包升级 ([39c2b2b](https://github.com/AntmJS/antm/commit/39c2b2b5d075aa40d2c3d1b593c3eed1f4af3c67))
* 更新import/order顺序 ([e0973a6](https://github.com/AntmJS/antm/commit/e0973a6d99b94e56591c7ad9238438b448901fc3))
* 错误被捕获的时候环境为development的状态下error出来 ([bcd47d2](https://github.com/AntmJS/antm/commit/bcd47d268a55a05d62bcd9026995761216b778d4))
* unite包添加错误收集及设置的方法 ([0f146f6](https://github.com/AntmJS/antm/commit/0f146f6d07a336941fe0d175b75ba585d10a0f0d))
* 优化主题变量 ([83be1bf](https://github.com/AntmJS/antm/commit/83be1bf9566f1ce6647a96071a49d97542e0da87))
* 修复border设置过细在支付宝端不展示的问题 ([0d0a0dc](https://github.com/AntmJS/antm/commit/0d0a0dc152883eabb95ad940763a7c …

chore(release): publish 1.13.2

---

lerna.json
packages/api/package.json
packages/babel-preset/package.json
packages/cache/package.json
packages/eslint/package.json
packages/global-state/package.json
packages/iconfont/package.json
packages/mini-fix/package.json
packages/mini-upload/package.json
packages/plugin-global-fix/package.json
packages/plugin-icestark/package.json
packages/plugin-mini-fix/package.json
packages/plugin-vantui/package.json
packages/rapper/package.json
packages/stylelint/package.json
packages/trace/package.json
packages/unite/package.json
packages/upload-tencent/package.json
packages/utils/package.json
packages/warning/package.json

* 添加@antmjs/api依赖包 ([81e8cdc](https://github.com/AntmJS/antm/commit/81e8cdcc7d1a8aede28f20751bf271b1bd6845fc))
* 新增api、删除vantuiCli、eslint错误 ([#101](https://github.com/AntmJS/antm/issues/101)) ([94e020e](https://github.com/AntmJS/antm/commit/94e020e658cb5e212183171a02dddabdae5bd3c6))
* 修复Unite内部异常 ([6763442](https://github.com/AntmJS/antm/commit/676344245cb810a4b0b3bac9b5fb191f975912a9))
* 修复utils工具解析query异常问题 ([0ee13e5](https://github.com/AntmJS/antm/commit/0ee13e5788bb5d1c170771df4feb7e36fd4108b4))
* 修复变量未引入的问题 ([8c8942c](https://github.com/AntmJS/antm/commit/8c8942c86bc999c8a9e656473c8b026b8eae686c))
* 添加plugin-global-fix插件 ([f88ce60](https://github.com/AntmJS/antm/commit/f88ce604925f9906ff8ba12bb0d11a2df81de180))
* 修复路径问题 ([60f5083](https://github.com/AntmJS/antm/commit/60f5083b4a70651b …

chore(release): publish 1.21.0

---

packages/api/src/swagger/createTypeFileName.ts
packages/api/src/swagger/transform.ts

close https://github.com/AntmJS/antm/issues/120

fix(swagger): 修复多标签问题，以及添加默认名称
